stages:
  - run

run_pipeline:
  stage: run
  before_script:
    # - pip install -r requirements.txt
    # - pip install dvc
  script:
    - dvc repro
    - dvc push
    - set TIMESTAMP=< output/timestamp.txt
    - git add dvc.lock
    - git commit -m "Updated dataset at %TIMESTAMP% and pushed to DVC remote"
